### ISSUE TITLE
Integration with Cloud Server

### ISSUE THREAD

**Issue by jtrombley90** [carbonblack/cb-yara-connector#9]
I've had some trouble with implementation on my cloud server. Does this work with the cloud servers?

**Comment by johnlockie** [comment]
I do not think so.  Last I checked (about a week ago), one of the major feature differences between the premise and cloud solutions is the ability to add custom threat intel feeds.  The Yara connector is essentially your own feed, therefore I would not be surprised if this is not supported.....I just changed companies and we are looking into rolling out Response, and we have a fleet of systems already on the carbonblack.io platform through a third party.  This is enough of a deal breaker for me that I am pushing to go premise.  We also run STIX connector....

**Comment by jtrombley90** [comment]
Yikes. That's not good news. There are multiple connectors I would be running and there is a big push for using the cloud in my org.

**Comment by jtrombley90** [comment]
Talking with a support rep, it looks like you can request that the connector be setup with the cloud service but must open a ticket with support. Hope that helps @johnlockie

**Comment by askthedragon** [comment]
This connector is supported in conjunction with the yara manager provided by the Cb Response Cloud team.
